### ISSUE TITLE
Response text in example cf 

### ISSUE THREAD

**Issue by reactiver001** [sarperavci/CloudflareBypassForScraping#1]
Hello , the first congrats for your example , 

Its possible help me to print response in your example  , when challenge is solve  ? i try find in guide but dont find nothing for this .
Thanks one more time

**Comment by sarperavci** [comment]
What do you mean by "response"

**Comment by reactiver001** [comment]
hello 

print response = print html information for page 

send for you example in playwright  ( this example dont passed cf , but print response html ) 


import asyncio
from playwright.async_api import async_playwright

async def main():
    arguments = [
        "-no-first-run",
        "-force-color-profile=srgb",
    ]

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True, args=arguments)
        page = await browser.new_page()
        await page.goto('https://nowsecure.nl')

        # Get the page content (response)
        content = await page.content()
        print(content)

        # Close the browser when done
        await browser.close()

if __name__ == "__main__":
    asyncio.run(main())



Understand ? thanks

**Comment by sarperavci** [comment]
you can print the content of the page like this:
```
print(driver.html)
print(driver.title)
```

**Comment by reactiver001** [comment]
Perfect , understand now , possible headless to ? because i try this : 


    for argument in arguments:
        options.set_argument(argument)
        headless=True

But dont work , you use discord or other plataform ?  thanks

**Comment by sarperavci** [comment]
you can contact me via https://twitter.com/sarperavci

**Comment by reactiver001** [comment]
Fixed =)
