### ISSUE TITLE
[macOS/windows&vpn]cloudflare infinite loop

### ISSUE THREAD

**Issue by frederik-uni** [sarperavci/CloudflareBypassForScraping#13]
clicking on the checkbox works, but as it is clicked it starts loading, after a while it returns to unchecked. it seems to be the same issue as this: https://github.com/FlareSolverr/FlareSolverr/pull/1163

clicking on it manually is working like expected & isn't causing this issue

**Comment by frederik-uni** [comment]
I tried reproducing the issue on linux, which I couldn't. I do not know if this issue affects windows or not. My guess is that this is an issue with the click implementation of DrissionPage on macOS. It would be great if someone who uses macOS can tell me if they have the same issue or if its the chrome version or something different

**Comment by frederik-uni** [comment]
The click doesn't work when I use a vpn. My guess is that the connection is suspicious and therefore checked differently

**Comment by sleepyzardo** [comment]
getting the same issue on a windows machine!

**Comment by sleepyzardo** [comment]
@sarperavci can you possibly look into this? its working when i manually open the dev tools but the click just returns none otherwise with no change!

**Comment by sleepyzardo** [comment]
![image](https://github.com/user-attachments/assets/cf7b38e7-65d3-4ade-903d-2c65b307bb37)
![image](https://github.com/user-attachments/assets/5b719df9-d154-4cc6-b7b8-f73726a4dd6d)

**Comment by sleepyzardo** [comment]
it doesnt click at all

**Comment by sarperavci** [comment]
As far as I understand from your comments, the script works fine if the developer console is open. As a workaround, we can try opening the dev console before starting the clicking process. I'm not available to check this right now, but I will do so as soon as possible and commit the changes. Feel free to make pull requests if you find a solution.

**Comment by sleepyzardo** [comment]
Thanks for your reply, however that has been patched as cf has pushed a new update. Im working to find a solution but cant as of now. Hopefully you can find a fix. Thankyou
