### ISSUE TITLE
run in headless mode or open window without grabbing focus?

### ISSUE THREAD

**Issue by darchon7** [sarperavci/CloudflareBypassForScraping#28]
right now every time the chrome window opens, it grabs focus which is distracting. is there a way to run this in headless mode or open without grabbing focus?

**Comment by sarperavci** [comment]
Can you set DockerMode = true on `server.py`, even if you not run it on Docker, it'll be headless.

**Comment by darchon7** [comment]
great tx, that worked perfectly!

**Comment by darchon7** [comment]
hmm I was wrong. it dsnt seem to be working now.

**Comment by sarperavci** [comment]
> hmm I was wrong. it dsnt seem to be working now.

what's the problem? can you share screenshots and terminal outputs to show?

**Comment by darchon7** [comment]
here's what I did, edit server.py, add
DOCKER_MODE = true

comment out: DOCKER_MODE = os.getenv("DOCKERMODE", "false").lower() == "true"

![Notepad_I8jEFsHBzc](https://github.com/user-attachments/assets/8df4e91a-e6df-42f3-b3b7-251f3defbeb8)

run test.py:

![WindowsTerminal_C1b0jolAoR](https://github.com/user-attachments/assets/35ee8fa6-9c8a-4087-8194-bcef59b83974)

the chrome window still appears:

![chrome_WYrzlqZZqX](https://github.com/user-attachments/assets/cb1fa259-4b5c-4903-a6c0-624a410bb17c)

**Comment by sarperavci** [comment]
Oh, sorry. I thought you were using `server.py`. I just committed headless support. Re-clone the repo and you can change `isHeadless=True` on line 34 in `test.py`.

**Comment by darchon7** [comment]
just cloned the repo again and added isHeadless=Trueto line 34 of test.py:
![Notepad_WEhsMCQbET](https://github.com/user-attachments/assets/9df6b579-b77f-4ceb-ba81-097169bb987a)

still didn't work and it opened a chrome window.

![WindowsTerminal_gY3h4uHysJ](https://github.com/user-attachments/assets/29c3b3b5-b6a3-4f5c-8205-42fafd5772ca)

**Comment by sarperavci** [comment]
Are you sure you have the latest version of the repo? https://github.com/sarperavci/CloudflareBypassForScraping/commit/729613653e0a2cab989362fcfbd446297646ce2a

**Comment by darchon7** [comment]
ok I deleted and recloned it and reinstalled the requirements, it added some new modules.

now there's this error:
![WindowsTerminal_12gHGjj1Tv](https://github.com/user-attachments/assets/3395e63f-07c9-4c54-898c-c79950d3cd71)

**Comment by sarperavci** [comment]
I am [not sure](https://stackoverflow.com/questions/43270513/is-there-a-windows-equivalent-to-pyvirtualdisplay) you can use the module we use for headless mode on Windows.

Creating your own Docker image as needed might solve your problem.

**Comment by frederik-uni** [comment]
its possible to run it headless on windows, but you would need to be implemented:
https://stackoverflow.com/questions/43270513/is-there-a-windows-equivalent-to-pyvirtualdisplay

**Comment by darchon7** [comment]
so I tried running:
docker build -t cloudflare-bypass .
docker run -p 8000:8000 cloudflare-bypass

and the docker image is running. but what do I do next? how do I configure test.py to go thru the docker image?
![WindowsTerminal_3Qe3c5i4mP](https://github.com/user-attachments/assets/aaec4cd5-b2a8-4e06-a8ff-e4fb99588f4d)

**Comment by darchon7** [comment]
ah nvm, I just needed to use the same syntax as server.py or use curl. tx!
