### ISSUE TITLE
Unable to retrieve HTML with cf-turnstile-response in server mode, ends quickly after opening the page

### ISSUE THREAD

**Issue by yqchilde** [sarperavci/CloudflareBypassForScraping#30]
test website: https://peet.ws/turnstile-test/managed.html

**Comment by sarperavci** [comment]
Can you share an output like this:

```sh
sarp@IdeaPad:~/$ curl http://localhost:8000/cookies?url=https://nopecha.com/demo/cloudflare
{"cookies":{"cf_clearance":"SJHuYhHrTZpXDUe8iMuzEUpJxocmOW8ougQVS0.aK5g-1723665177-1.0.1.1-5_NOoP19LQZw4TQ4BLwJmtrXBoX8JbKF5ZqsAOxRNOnW2rmDUwv4hQ7BztnsOfB9DQ06xR5hR_hsg3n8xteUCw"},"user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36"}
```

**Comment by yqchilde** [comment]
I have added a video of my operation.

https://alist.diyy.fun:433/Public/2024-08-16%2022.55.57.mov

**Comment by sarperavci** [comment]
Add some sleep time after `driver.get()` and change `cf_bypasser.bypass()` to `cf_bypasser.click_verification_button()`

https://github.com/sarperavci/CloudflareBypassForScraping/blob/729613653e0a2cab989362fcfbd446297646ce2a/server.py#L79-L81

These should solve your problem.

**Comment by yqchilde** [comment]
> Add some sleep time after `driver.get()` and change `cf_bypasser.bypass()` to `cf_bypasser.click_verification_button()`
> 
> https://github.com/sarperavci/CloudflareBypassForScraping/blob/729613653e0a2cab989362fcfbd446297646ce2a/server.py#L79-L81
> 
> These should solve your problem.

This method may not be 100% effective and can be time-consuming. I'm thinking of other ways
1. Sleep is not required, it should be done through wait.eles_loaded()
2. Shadow roll, I have seen that it has been checked many times, but it is quite time-consuming here

**Comment by yqchilde** [comment]
curl http://127.0.0.1:8000/html?url=https://peet.ws/turnstile-test/managed.html&retries=5

Sorry, the route I mentioned is /html
