### ISSUE TITLE
Shadow root closed issue

### ISSUE THREAD

**Issue by Rakeshbiswal01** [sarperavci/CloudflareBypassForScraping#49]
I am facing shadow root closed issue.i can't grab Element inside it 

First of all the checkbox is inside
A div then shadow root closed then iframe then shadow root and then checkbox

If try to open shadow root it gives error while click and doesnt give sucess response and cdp method doesn't work .

I want a method to get the bounding box of checkbox piercing shadow root closed or any thing else .in that way can make bypass turnstile.

**Comment by sarperavci** [comment]
Are you using our script?

I just run `test.py` and there's no problem.

```bash
sarp@IdeaPad:/tmp/CloudflareBypassForScraping$ python3.10 test.py 
2024-11-06 13:03:12,458 - INFO - Navigating to the demo page.
2024-11-06 13:03:13,103 - INFO - Starting Cloudflare bypass.
Attempt 1: Verification page detected. Trying to bypass...
Verification button found. Attempting to click.
Bypass successful.
2024-11-06 13:03:18,090 - INFO - Enjoy the content!
2024-11-06 13:03:18,091 - INFO - Title of the page: NopeCHA - CAPTCHA Demo
2024-11-06 13:03:23,097 - INFO - Closing the browser.
```

**Comment by Rakeshbiswal01** [comment]
I am telling about CF turnstile not waf.
It gives fraud error

And I didn't used drissionpage.but is drissionpage really can bypass shadow root closed ?

**Comment by sarperavci** [comment]
Yes, our script gets through the closed shadow. This is already for cf turnstile. Not waf.

**Comment by Rakeshbiswal01** [comment]
Cf turnstile means the turnstile captcha appears at proxyscape login and signup

I am using playwright python .can you help me with that?

**Comment by Rakeshbiswal01** [comment]
@sarperavci help bro
